// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/live.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Live.tsx";
import * as $$2 from "./islands/Offline.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/live.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Live.tsx": $$1,
    "./islands/Offline.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
